### PR TITLE
Update users.md

### PR DESCRIPTION
**Pull request by zstadler**
Attempting to remove a decrease in indentation and a reset of numbering:

image

### CODE REVIEW

**Comment by grst** [comment]
The table isn't rendered properly here ... maybe you'll need to merge in the current master branch? 
btw, you can see how the page renders by clicking on "Details" next to the readthedocs check.

**Comment by zstadler** [comment]
As far as I can see, this branch is based in the latest `master`.
Thanks for the hint about readthedocs!

It seems that this is a limitation of the newly added `sphinx_markdown_tables` package.
- If there is a blank line before the table, it breaks-out of the indentation and resets its dependent numbering
- If there is no blank line before the table, the table is not recognized as such.

The table seems to be wider than the available space on the readthedocs page, so I tried to convert it into a list. Please let me know what you think.

I'd also like to suggest to split the **Running GEOS in a docker container** section into two sub-sections: **Using Docker** and **Using Docker Compose**. I'd also like to suggest  some simplification for the Docker Compose setup.

If that's OK with you, I'll be happy to send a separate PR for that.

**Comment by zstadler** [comment]
For some reason, the [details](https://geos--36.org.readthedocs.build/en/36/) link for the _Read the Docs_ check show the broken table, although the source code in this PR does not have a table any more.

image

**Comment by grst** [comment]
I had some caching issues with RTD before... try Ctrl+F5

**Comment by zstadler** [comment]
Numbering is now restored:

image

BTW, on Ubunto 20.04, the documented way to find the IP address of the server is not working well

```
$ ip route get 1 | awk '{print $NF;exit}'
1001
```
because
```
$ ip route get 1
1.0.0.0 via 10.10.10.10 dev eth0 src 10.10.10.21 uid 1001 
    cache 
```
Please let me know if you want me to change it to this:
```
$ ip route get 1| sed 's/.* src \([0-9.]*\) .*/\1/;q'
10.10.10.21
```

**Comment by grst** [comment]
> Please let me know if you want me to change it to this:

Your snippet works on my arch system, too. Feel free to change it :)

**Comment by zstadler** [comment]
> 
> 
> > Please let me know if you want me to change it to this:
> 
> Your snippet works on my arch system, too. Feel free to change it :)

Done!

**Comment by zstadler** [comment]
Perhaps the Docker-related sections should be moved under "Installation" instead of "Creating Mapsources"

image

I would also recommend positioning the simpler Docker Compose approach before the raw Docker approach.
IMHO, you may also consider removing the raw Docker approach all together, but I'm biased 🙂 .

**Comment by grst** [comment]
> Perhaps the Docker-related sections should be moved under "Installation" instead of "Creating Mapsources"

Good point, actually, no idea why I put it there. 

> I would also recommend positioning the simpler Docker Compose approach before the raw Docker approach.

I'm fine with removing it. When I wrote this section I was still very new to docker, but now I'm also using docker-compose for everything.

**Comment by grst** [comment]
Lgtm, thanks!

**Pull request merged**
